TODO
	- Fixing the new line problem in Helper
	- Why is the "Exception in thread "main" thrown"